### ISSUE TITLE
segfault on windows 64

### ISSUE THREAD

**Issue by thirdwing** [thirdwing/RcppMLPACK1#18]
```
> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: mlKmeans
> ### Title: kmeans from MLPACK
> ### Aliases: mlKmeans
> 
> ### ** Examples
> 
>   data(trees, package="datasets")
>   mlKmeans(t(trees),3)

error: arma::memory::acquire(): out of memory
Error in mlKmeans(t(trees), 3) : std::bad_alloc
Calls: mlKmeans -> .Call
```

**Comment by coatless** [comment]
That's new...

**Comment by rcurtin** [comment]
The trees dataset is tiny, right?  My guess here is some value is being passed wrong somewhere and Armadillo is trying to allocate a 2^64 - 1 by 2^64 - 1 matrix or something like this.  Maybe this is not very helpful but it may be a step in the right direction if someone has not already stepped that way. :)

**Comment by eddelbuettel** [comment]
It is tiny, but we've had that example since forever.  

Maybe it is 'just' the downcasting from the (transposed) data.frame to a matrix which causes problems...

**Comment by eddelbuettel** [comment]
I tried to rhub, it timed out. I don't have it in me to work on the Windows VM.

Maybe time for a triage.  Get RcppMLPACK1 off life-support for a few days, or focus on RcppMLPACK2.   If @coatless is right it would be the same Arma bug anyway...

**Comment by eddelbuettel** [comment]
And while I type this you found the fix?  Nice job, @thirdwing.

**Comment by thirdwing** [comment]
Actually it should be a stupid mistake. I will come back very soon.

**Comment by eddelbuettel** [comment]
Just a fact of old code we had left to the side for a while -- Conrad did change the index type.
